# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_employee_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCompanyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name=b'Assunto')),
                ('message', models.TextField(verbose_name=b'Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_messages', to='account.Employee')),
            ],
            options={
                'verbose_name': 'Fale conosco',
                'verbose_name_plural': 'Fale conosco',
            },
        ),
        migrations.CreateModel(
            name='FormMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name=b'Assunto')),
                ('message', models.TextField(verbose_name=b'Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_messages', to='account.ConsumerUser')),
            ],
            options={
                'verbose_name': 'Fale conosco',
                'verbose_name_plural': 'Fale conosco',
            },
        ),
    ]
