# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name=b'CNPJ')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Raz\xe3o social')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 1')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2')),
                ('active', models.BooleanField(default=1, verbose_name=b'Ativo')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='total')),
                ('deleted', models.BooleanField(default=0, verbose_name=b'Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Address', verbose_name='Endere\xe7o')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='company.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ConsumerUser')),
            ],
        ),
    ]
